"""topic_embeddings_chunk

Revision ID: 9bf631a54cbd
Revises: a88528cc2d55
Create Date: 2026-01-19 12:42:41.479321

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bf631a54cbd"
down_revision: Union[str, Sequence[str], None] = "a88528cc2d55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topic_embeddings", sa.Column("chunk", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic_embeddings", "chunk")
    # ### end Alembic commands ###
