"""image url

Revision ID: 0ad903781722
Revises: ed75a08e4bf6
Create Date: 2026-01-22 16:49:53.950337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ad903781722"
down_revision: Union[str, Sequence[str], None] = "ed75a08e4bf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("image_url", sa.String(), nullable=True))
    op.add_column("topic_embeddings", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic_embeddings", "image_url")
    op.drop_column("messages", "image_url")
    # ### end Alembic commands ###
